movieapp/urls.py
from django.urls import path
from . import views

app_name = 'movieapp'

urlpatterns = [
    path('',views.index,name="index"),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

movieapp/models.py
from typing import Any
from django.db import models

# Create your models here.

class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name
    

movieapp/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

movieapp/views.py
from django.shortcuts import redirect, render,HttpResponse
from . models import Movie
from . forms import MovieForm

# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movies_list': movie
    }
    return render(request,"index.html",context)

def detail(request,movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')

def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form': form,'movie':movie})

def delete(request,id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the movie name">
    <input type="text" name="desc" placeholder="Enter the Description">
    <input type="text" name="year" placeholder="Enter the Year">
    <input type="file" name="img" placeholder=" Select Image file">
    <input type="submit">

</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"> Online Movie Store </a>
      </div>
    </nav>
    {% block body %}
    {% endblock %}
  </body>
</html>

templates/delete.html
<form  method="post">
    {% csrf_token %}
    Do you want to delete this movie?
    <input type="submit">
</form>

templates/detail.html
{% extends 'base.html' %} {% block body %}

<br>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img src="{{movie.img.url}}" width="400" height="450" /> <br />
    </div>
    <div class="col-md-6">
        <h2>{{movie.name}}</h2><br />
        {{movie.desc}}<br /><br>
        {{movie.year}}<br /><br>
        <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}"
      >Update</a
    >
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id%}"
      >Delete</a
    >
    </div>

    
    
  </div>
</div>

{% endblock %}

templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

templates/index.html
{% extends 'base.html' %}

{% block body %}
<br>

<div class="container">
    <div class="row">
        {% for i in movies_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="250px" height="300px">
                <div class="card-body">
                  <h5 class="card-title">{{ i.name }}</h5>
                  <p class="card-text">{{ i.year }} </p>
                  <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Detail</a>
                </div>
              </div>
              <br>
        </div>
        
        {% endfor %}
    </div>
</div>





{% endblock %}